# Generated by Django 3.2.7 on 2021-10-19 23:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title', max_length=40, verbose_name='Title')),
                ('desc', models.CharField(blank=True, help_text='Description', max_length=400, null=True, verbose_name='Description')),
                ('date', models.DateField(help_text='Day of the event', verbose_name='Day of the event')),
                ('start', models.TimeField(default='12:00', help_text='Start time', verbose_name='Start time')),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=25)),
                ('last', models.CharField(max_length=25)),
                ('age', models.PositiveIntegerField()),
                ('tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='member', to='fwn_app.tag')),
            ],
        ),
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('desc', models.CharField(max_length=400)),
                ('upper_age', models.IntegerField(default=110)),
                ('lower_age', models.IntegerField(default=18)),
                ('event', models.ManyToManyField(related_name='idea', to='fwn_app.Event')),
                ('members', models.ManyToManyField(related_name='idea', to='fwn_app.House')),
                ('tag', models.ManyToManyField(related_name='idea', to='fwn_app.Tag')),
            ],
        ),
        migrations.AddField(
            model_name='house',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='member', to='fwn_app.member'),
        ),
        migrations.AddField(
            model_name='house',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='house', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='rsvp',
            field=models.ManyToManyField(blank=True, related_name='event', to='fwn_app.Member'),
        ),
    ]
