# Generated by Django 3.2.7 on 2021-10-15 03:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fwn_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='user',
        ),
        migrations.AddField(
            model_name='ideas',
            name='lower_age',
            field=models.IntegerField(default=18),
        ),
        migrations.AddField(
            model_name='ideas',
            name='upper_age',
            field=models.IntegerField(default=110),
        ),
        migrations.AlterField(
            model_name='ideas',
            name='event',
            field=models.ManyToManyField(related_name='ideas', to='fwn_app.Events'),
        ),
        migrations.CreateModel(
            name='Houses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='houses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='events',
            name='rsvp',
            field=models.ManyToManyField(related_name='events', to='fwn_app.Houses'),
        ),
        migrations.AddField(
            model_name='ideas',
            name='members',
            field=models.ManyToManyField(related_name='ideas', to='fwn_app.Houses'),
        ),
    ]
