# Generated by Django 3.2.8 on 2021-10-29 18:25

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fwn_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 29, 11, 24, 59, 812484)),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 29, 11, 24, 59, 812484)),
        ),
        migrations.AlterField(
            model_name='idea',
            name='event',
            field=models.ManyToManyField(related_name='ideas', to='fwn_app.Event'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='tag',
            field=models.ManyToManyField(related_name='ideas', to='fwn_app.Tag'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ideas', to=settings.AUTH_USER_MODEL),
        ),
    ]
