# Generated by Django 3.2.7 on 2021-10-15 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fwn_app', '0002_auto_20211014_2007'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='ideas',
            name='desc',
            field=models.CharField(default='', max_length=400),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='ideas',
            name='tag',
        ),
        migrations.AddField(
            model_name='ideas',
            name='tag',
            field=models.ManyToManyField(related_name='ideas', to='fwn_app.Tags'),
        ),
    ]
