# Generated by Django 3.2.8 on 2021-10-29 22:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fwn_app', '0003_auto_20211029_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 29, 15, 41, 55, 74993)),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 29, 15, 41, 55, 74993)),
        ),
    ]
