# Generated by Django 3.2.7 on 2021-10-15 18:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fwn_app', '0003_auto_20211014_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('desc', models.CharField(max_length=400)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='house', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('desc', models.CharField(max_length=400)),
                ('upper_age', models.IntegerField(default=110)),
                ('lower_age', models.IntegerField(default=18)),
                ('event', models.ManyToManyField(related_name='idea', to='fwn_app.Event')),
                ('members', models.ManyToManyField(related_name='idea', to='fwn_app.House')),
            ],
        ),
        migrations.RemoveField(
            model_name='houses',
            name='user',
        ),
        migrations.RemoveField(
            model_name='ideas',
            name='event',
        ),
        migrations.RemoveField(
            model_name='ideas',
            name='members',
        ),
        migrations.RemoveField(
            model_name='ideas',
            name='tag',
        ),
        migrations.RenameModel(
            old_name='Tags',
            new_name='Tag',
        ),
        migrations.DeleteModel(
            name='Events',
        ),
        migrations.DeleteModel(
            name='Houses',
        ),
        migrations.DeleteModel(
            name='Ideas',
        ),
        migrations.AddField(
            model_name='idea',
            name='tag',
            field=models.ManyToManyField(related_name='idea', to='fwn_app.Tag'),
        ),
        migrations.AddField(
            model_name='event',
            name='rsvp',
            field=models.ManyToManyField(related_name='event', to='fwn_app.House'),
        ),
    ]
