# Generated by Django 3.2.7 on 2021-10-21 23:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fwn_app', '0004_auto_20211021_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(verbose_name='Day of the event'),
        ),
        migrations.AlterField(
            model_name='event',
            name='desc',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 21, 16, 55, 47, 539934)),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 21, 16, 55, 47, 539934)),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=40, verbose_name='Title'),
        ),
    ]
