# Generated by Django 3.2.7 on 2021-10-21 23:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fwn_app', '0005_auto_20211021_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='date',
        ),
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 21, 16, 56, 27, 649384)),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 21, 16, 56, 27, 649384)),
        ),
    ]
