# Generated by Django 3.2.9 on 2021-11-04 23:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fwn_app', '0006_auto_20211104_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='State',
            field=models.CharField(max_length=16, null=True, verbose_name='State'),
        ),
        migrations.AddField(
            model_name='event',
            name='city',
            field=models.CharField(max_length=40, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='event',
            name='street_address',
            field=models.CharField(max_length=40, null=True, verbose_name='Street Address'),
        ),
        migrations.AddField(
            model_name='event',
            name='zipcode',
            field=models.CharField(max_length=10, null=True, verbose_name='Zipcode'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 4, 16, 48, 11, 331548)),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 4, 16, 48, 11, 331548)),
        ),
    ]
