# Generated by Django 3.2.9 on 2021-11-05 04:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fwn_app', '0008_auto_20211104_1750'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='State',
            new_name='state',
        ),
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 4, 21, 58, 40, 761324)),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 4, 21, 58, 40, 761324)),
        ),
    ]
