# Generated by Django 3.2.9 on 2021-11-05 17:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fwn_app', '0011_auto_20211105_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='street_address',
            field=models.CharField(max_length=40, null=True, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 5, 10, 33, 10, 647510)),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 5, 10, 33, 10, 647510)),
        ),
    ]
